name: Trigger grader on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dispatch-to-grader:
    runs-on: ubuntu-latest
    steps:
      # Получаем installation-token вашего GitHub App для репозитория грейдера
      - name: App token for grader repo
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}                 # <- ID GitHub App
          private-key: ${{ secrets.APP_PRIVATE_KEY }}   # <- PEM GitHub App
          owner: mireajava                    # <- замените
          repositories: java-course-grading             # <- имя репо с приватными тестами

      - name: Send repository_dispatch to grader
        env:
          GH_TOKEN:   ${{ steps.app.outputs.token }}
          GRADER_OWNER: mireajava
          GRADER_REPO:  java-course-grading
          STUDENT_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          STUDENT_REF:  ${{ github.event.pull_request.head.ref }}
          STUDENT_SHA:  ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Dispatching to ${GRADER_OWNER}/${GRADER_REPO} for ${STUDENT_REPO}@${STUDENT_SHA} (${STUDENT_REF})…"
          gh api -i repos/${GRADER_OWNER}/${GRADER_REPO}/dispatches \
            -f event_type=grade-request \
            -f client_payload:="{\"repo\":\"${STUDENT_REPO}\",\"branch\":\"${STUDENT_REF}\",\"sha\":\"${STUDENT_SHA}\"}"
          echo "✅ repository_dispatch sent."
