name: Forward PR to grader

on:
  # работает для PR из форков и имеет доступ к secrets базового репо
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  forward:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to java-course-grading
        env:
          # секрет в БАЗОВОМ репо mireajava/prnumber1:
          # PAT (classic) со scope: public_repo (или repo, если грейдер/форки приватные)
          GH_TOKEN: ${{ secrets.GRADING_TRIGGER_PAT }}
          OWNER:   ВАШ_АККАУНТ_ИЛИ_ОРГ         # ← замените
          GRADER:  java-course-grading
          REPO:    ${{ github.event.pull_request.head.repo.full_name }}
          BRANCH:  ${{ github.event.pull_request.head.ref }}
          SHA:     ${{ github.event.pull_request.head.sha }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${GH_TOKEN:-}" ]; then
            echo "::error::Нет секрета GRADING_TRIGGER_PAT в базовом репозитории."
            exit 1
          fi

          echo "PR from: $REPO"
          echo "Branch : $BRANCH"
          echo "SHA    : $SHA"

          # Отправляем сигнал в грейдер и выводим код ответа для диагностики
          HTTP_CODE=$(curl -sS -w "%{http_code}" -o /tmp/resp.txt \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${GRADER}/dispatches" \
            -d "{\"event_type\":\"grade-request\",\"client_payload\":{\"repo\":\"${REPO}\",\"branch\":\"${BRANCH}\",\"sha\":\"${SHA}\"}}")

          echo "GitHub API status: ${HTTP_CODE}"
          echo "Response body:"
          cat /tmp/resp.txt || true

          # Успех — 204
          if [ "$HTTP_CODE" != "204" ]; then
            echo "::error::Не удалось отправить repository_dispatch (ожидали 204). Проверьте OWNER/GRADER и права токена."
            exit 1
          fi
          echo "✅ Dispatch delivered."
