name: Build check

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Compile sources
        run: javac $(find src/main/java -name "*.java")

      - name: Notify student
        run: |
          echo "✅ Код скомпилирован."
          echo "Полная проверка выполняется у преподавателя."
