name: Build check

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure repository is PUBLIC
        if: ${{ github.event.repository.private }}
        run: |
          echo "❌ Этот форк приватный. Для автопроверки сделайте репозиторий PUBLIC (или дайте преподавателю доступ)."
          exit 1

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Compile sources
        run: |
          FILES=$(find src/main/java -name "*.java")
          if [ -z "$FILES" ]; then
            echo "❌ В каталоге src/main/java не найдены .java файлы."; exit 1
          fi
          javac $FILES
          echo "✅ Код скомпилирован."

      - name: How to run hidden tests
        run: |
          echo "Откройте Pull Request в основной репозиторий:"
          echo "https://github.com/mireajava/prnumber1/compare/main...${GITHUB_REPOSITORY%/*}:${GITHUB_REF_NAME}?expand=1"
          echo "После открытия PR приватные тесты запустятся автоматически, а логи появятся в комментариях к вашему коммиту."
